services:
  backend: 
    build:
      context: ./back_end
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    volumes: 
      - ./data:/usr/src/app/data
    container_name: backend

  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: frontend

    
